agent_settings:
  concurrent_tasks:
    background: 3
    bgm: 2
    cg: 2
    portrait: 3
    voice: 5
  enable_agents:
    background_agent: false
    bgm_api: false
    cg_agent: false
    plot_agent: true
    portrait_agent: false
    voice_api: false
  retry_settings:
    max_retries: 3
    retry_delay: 5
api_keys:
  claude:
    api_key: ENC::gAAAAABpbFzYDDVTh9rauMn6JKMuJuyDxEG-Ij5bb97iz94fLQYI4qAlGTM7E8ovn3y90lpOV9E5h3YfrJsObMOUkK-BMVQKtXVZ2TzADnd9V1y0r7v6Zs9MzalLN7DFeAEperTC4uUClQZ1lTVm2c44bq8jsJa0-1yvuJV9TyA9LsPui6HHlT0NreOY-xD76Mhl7UnynXHammostpry6oqrakkFn-G1qGBNkoBboy7eNP-TCNTa-QazTNTuiy4tBlIHqRGJByZTlDUKUyJ8wIcJ5wRFLAnqbRKRSKlkK29TUqfMTqKrmHdkrDiZ--W75rT9W2eBf4EB3UDdemjA_F-xpnlvV6IGpVMOTq4pOzGpppduU24ILlnHHW99yuqhbKblMeYv3KFbKy_b1XyMP4wBWoC2ZFJg-dEYRsUIZkDHuo3UF8EybZV-v6TjhbFDCdLogYLyl9B-
    base_url: https://llm-api.mmchat.xyz
    fallback_model: claude-sonnet-4-5-20250929
    primary_model: claude-sonnet-4-20250514
  flux:
    api_key: ENC::gAAAAABpbFzYToGIIDENoacRg3r8hUcYRc3jbT2s5UUpbyBcjGNe5RyTI6DLkiHOy2hMRIj2LmXrUYoGh4WJ9gtcii9oThxkQSwrGb532K2Y96ETig_YWLRG-hFfcC0ki-yFX1RSDgi50ucfxkVcbjenkg4L7uVsM4Gur4lUEWBW2kbZ_1MHoDdTdcUGPLmhoCdRw8GkVaIguujuwcXgHa7SZM82prL2IALmmeIS88mcTJq8JP4FGx4H6peXyoSm3qzDymNS6BRg6NFvL4_wZ0BTHBPbTG4IIMxoTKnHVve5XrIwK4qwZVtEHoqZzoyCH6lBrCe_QcTBWNMciR_DTmY8xs-GyG7iH_9EeFet0ECIay5hOPzO1bTn5DYIRGeBI0LdDynaFkypsbGP115JcGpLP5-aellzlEOWhvMLw6N0rPp9YgOyx0Epn3Ob0ZTyia9e3-Zpwyqy
    app_id: 5c80d2bc149d17f136152c771d5ba7cb
    base_url: https://api.mmchat.xyz
    fallback_model: flux-2-pro
    primary_model: flux-kontext
  gptsovits:
    api_key: ENC::gAAAAABpbFzYjtbDT7-dxW3MXJrTtAECbNkudJjDPkW09v_IckCESwsASPB6NoPDmqw6MWVc7qObSrTlLhaL1l1oqd7qvlXlpSdm6RjoOTF-S9P-rPNc7VpTrhZCjl_KB52BvCxrp8my
    base_url: https://openapi.lipvoice.cn
    fallback_model: ''
    primary_model: ''
    sign: ENC::gAAAAABpbFzY_-0aORBz08TEtQ8kGzTKiJ9tCcMm4IdmuyVik3bZ5uSHJ0cw98AUycIM1KWWI59DpmbBhhO-Xxvb69bdwFn-BZRZjA4g7BTJHQp_h-7ZMaHvOKY-MZQTrpkRM1bIP0g_
  kimi:
    api_key: ENC::gAAAAABpbFzYZt55KlmM76Fd5SzHashDlGC3HCP0dcgtOJ6BKx9moVF3MTs1scLwO222d4Kb1rUb5n3c8DisoX4rmZ6G-1Ue0prA_H1TMNkWZjaccWWsrarwLBo0NY-I9yP__z-EOPbDWqJyj9dG55lAroCw-6NAn4ODeF1d2zlUZ1uD8hQGT7s6iF0q0WMXcS505whNdO_zoBwV3ZxSB8fDD74uHB_gsBxdekb7N-R7xyMV8pU591hP3CcC-CSOn5Eqz3m32KNic1v3D82JT7dVxeXAVYnqrXIMzceOvaFBCmBncpHLZ6zZySJxMXGNq5vE0pN-RWrXMds88m20ZUB16BRtnSlkPj-5KiJszt5Ngw-GPo6ra6h2cT22avuEC0NUD4sZC76EdulQW7TvlhkfLYp4WB4XmuGV8h0WYxgL5h6jpsFG9CbpZqNTHmxZeB62BF-7v4xG
    base_url: https://llm-api.mmchat.xyz
    fallback_model: anthropic/kimi-k2-thinking
    primary_model: anthropic/kimi-k2-0905-preview
  midjourney:
    api_key: ENC::gAAAAABpbFzYIp2hWlVGHTfEBGeFN1FqvZtC25FB8KfL0EqJD4JKUE7k32QO2QbDgSdF4YkK-tSuffqi0YiytAchjcKYnqSpMHX0M7tQwP8YvXxBlg8a-fn817KENm0py1Q4iUPTexdu1wdWVkMP2CX1fPgdCTdgD6dCRrsZoJAFVU582sT8Hfz728JItv20YXm2p5lZUU3_glnD2fhBAgTZlDOzD2JT2u19kdG_3_ZpGSvIGQ7_SDUw7yp7NJiwdYwY4IFCg5EnODvuSlTz2TcWKm27IkDAynH6zVTjoj0PtBLghkYnw9uS3l09EgWpuLfA01BKvXDgFU10q3J8oEKfG8LMEtDyMy2QoZJyUnHQoPOetQae4v6Gorw8vFyHMyl6f3wSBDsayByviTfNisbqYEZ72E3hoSftap2In68Nehi35-PiMe1DG5txGG10kHaMID6yEmqV
    app_id: 5c80d2bc149d17f136152c771d5ba7cb
    base_url: https://api.mmchat.xyz
    fallback_model: mj-v61
    primary_model: mj-v7
  suno:
    api_key: ENC::gAAAAABpbFzY16oOufn6V1x7vP9RAbcn-T37lM2qhhoL_Fo9QLYNMECcI-POle4Tmb5ww__KbQvXTS8UXSfs3n3GqdWc9oNXqc9YZq6GFSnA3xMJaqoCAfPj_4TQDLF0vOTwwWNOess1
    base_url: https://dzwlai.com/apiuser
    fallback_model: chirp-v4-5+
    primary_model: chirp-v5
    token: ENC::gAAAAABpbFzY6-ZnLf0tZRWS9dMPXVJBgoJqsDGaqb6LoB8ygx58hkLii5I56xzhvUXmcfLQQM26ZHyYA5hlCz8Mr_QceO9_bTdWkYWhg38sHg73ekdMQk-zrprj78z-QkWC_f5zEJLa
    user_id: '17328098894'
character_config:
- char_id: 夏栀
  char_name: 夏栀
  is_first_person: false
  persona_keywords: 我的同班同学，开朗温柔，喜欢绘画，是班级里的文艺委员，笑起来有两个浅浅的梨涡
  role: 女主角
  voice_model_id: ABuUZoqCrNhK3YS8UQEsKTdPRo
- char_id: 林屿
  char_name: 林屿
  is_first_person: true
  persona_keywords: 高二学生，性格略显内向，喜欢摄影，习惯用相机记录生活点滴，对夏日的校园有着特殊的眷恋。
  role: 男主角
  voice_model_id: 语音模型ID
material_settings:
  background:
    format: jpg
  bgm:
    format: mp3
  cg:
    format: png
  portrait:
    format: png
  voice:
    format: mp3
project_settings:
  auto_save_interval: 300
  default_window_height: 720
  default_window_width: 1280
  engine_version: V2.0-AI
  project_name: AItest
  resource_root: C:/Users/jerry/Desktop/test
story_config:
  character_hint_weight: 0.7
  first_person_cg_notes: ''
  first_person_cg_presence: false
  first_person_has_portrait: false
  first_person_has_voice: false
  first_person_name: 林屿
  narrative_pov: first
  plot_outline: '角色设定

    1. （我）男主：林屿 - 高二学生，性格略显内向，喜欢摄影，习惯用相机记录生活点滴，对夏日的校园有着特殊的眷恋。

    2. 女主：夏栀 - 林屿的同班同学，开朗温柔，喜欢绘画，是班级里的文艺委员，笑起来有两个浅浅的梨涡。

    高二学生林屿（我）（内向摄影爱好者）与同班开朗温柔的绘画爱好者夏栀，在教学楼后的梧桐树荫下因意外碰撞相识。两人因对夏日校园光影的共同喜爱产生共鸣，夏栀推荐林屿去天台拍夕阳，两人一同前往天台创作。林屿忍不住拍下晚霞中作画的夏栀，这份青涩的欣赏让彼此心生悸动，林屿借此鼓起勇气邀请夏栀暑假一同去海边看晚霞拍照，夏栀欣然应允并赠送手绘约定信物。暑假第一天，两人带着各自的创作工具在校园大门相遇，怀揣着期待并肩前往海边，开启属于他们的夏日独家回忆。'
  style: 青春校园恋爱
  text_volume: 1000
  title: 夏日回忆
